server:
  port: 8000

token:
  expiration_time: 7200000
  refresh_time: 86400000
  secret: 'token_secret'
  public: MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEA98960Kfh9QjHTU5Ig6m+iiBjQCXkkX2uMQqjam0JVdk+4MwRMZdTG4Tey2GhL0ja841KBDmYT7Bsxb80KmQ2GpzZfuFnqZc/fqF58SI8XRcIe8NxK1/IOrJX9A3TEZknHLzjnvyhctyFsIiGO+tGRtHIJR/7kUE0zMD5c+UR/VBXzbL5QNcTcK+PikLvLwz6PC0AZWtRJJ31Rca1w4qz4SzYXF0fQFGGPIF/Z4Jt4TcbfsrZLj+DjasbR309oWZj81FwBgw77ULU/Lt+QPG9A4eVJGKNhmCbyarwUbNsMAwjCjuJYVQY3K/ZBZ/1HU3CF2YAVC7RWuIB2DuMxirpZEwAy0FfwVbOpc7P4JMVz35aVL2zHA/+nxyZNSY9fzPQxXkoKN5C6i0ldExoqksH2zaqMqWNCnQO+hATv0rQN5j30rbYLThHysPlJGVPJ0f7/CClXLlCTKc209XY5e2eQfyCrRquTMpjzvhx9gAgVADFoIJQHca5xvtLT1//86tRAgMBAAE=

spring:
  application:
    name: apigateway
  cloud:
    gateway:
      routes:
        #        - id: user-service
        #          uri: lb://USER-SERVICE
        #          predicates:
        #            - Path=/user-service/**
        #          filters:
        #            - RemoveRequestHeader=Cookie
        #            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
        #        - id: portal-service
        #          uri: lb://PORTAL-SERVICE
        #          predicates:
        #            - Path=/portal-service/**
        #          filters:
        #            - RewritePath=/portal-service/(?<segment>.*), /$\{segment}
        #        - id: shop-service
        #          uri: lb://SHOP-SERVICE
        #          predicates:
        #            - Path=/shop-service/**
        #          filters:
        #            - RewritePath=/shop-service/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member-service/**
          filters:
            - RewritePath=/member-service/(?<segment>.*), /$\{segment}
        - id: backend5-service
          uri: lb://BACKEND5-SERVICE
          predicates:
            - Path=/backend5-service/**
          filters:
            - RewritePath=/backend5-service/(?<segment>.*), /$\{segment}
        #        - id: board-service
        #          uri: lb://BOARD-SERVICE
        #          predicates:
        #            - Path=/board-service/**
        #          filters:
        #            - RewritePath=/board-service/(?<segment>.*), /$\{segment}
        #        - id: reserve-item-service
        #          uri: lb://RESERVE-ITEM-SERVICE
        #          predicates:
        #            - Path=/reserve-item-service/**
        #          filters:
        #            - RewritePath=/reserve-item-service/(?<segment>.*), /$\{segment}
        #        - id: reserve-check-service
        #          uri: lb://RESERVE-CHECK-SERVICE
        #          predicates:
        #            - Path=/reserve-check-service/**
        #          filters:
        #            - RewritePath=/reserve-check-service/(?<segment>.*), /$\{segment}
        #        - id: reserve-request-service
        #          uri: lb://RESERVE-REQUEST-SERVICE
        #          predicates:
        #            - Path=/reserve-request-service/**
        #          filters:
        #            - RewritePath=/reserve-request-service/(?<segment>.*), /$\{segment}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<segment>.*), /$\{segment}/v3/api-docs
      default-filters:
        - name: GlobalFilter
          args:
            preLogger: true
            postLogger: true
      discovery:
        locator:
          enabled: true
    config:
      uri: http://localhost:8888
      name: application
# config server actuator
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

info:
  app:
    name: Spring Cloud Gateway
    description: API 라우팅 및 보안, 모니터링/메트릭 등의 기능을 간단하고 효과적인 방법으로 제공
  swagger-ui: http://localhost:8000/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

springdoc:
  api-docs:
    version: OPENAPI_3_0

messages:
  directory: ${user.dir}/msa-attach-volume/messages